CREATE TABLE IF NOT EXISTS log(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    category VARCHAR(255) NOT NULL ,
    level VARCHAR(255) NOT NULL ,
    system_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS system(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(80) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE log ADD CONSTRAINT FKjo7173o065h9iwe4nnkyo89iv FOREIGN KEY (system_id) REFERENCES system(id);

INSERT INTO system(name)
VALUES('System X');

INSERT INTO log(title, detail, category, level, system_id)
VALUES('Título do erro', 'Detalhe do Erro', 'DEVELOPMENT', 'ERROR', 1);
