CREATE TABLE IF NOT EXISTS log(
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  origin VARCHAR(50) NOT NULL,
                                  title VARCHAR(50) NOT NULL,
                                  detail VARCHAR(255) NOT NULL,
                                  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                                  category VARCHAR(255) NOT NULL ,
                                  level VARCHAR(255) NOT NULL ,
                                  user_id BIGINT,
                                  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user(
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   name VARCHAR(80) NOT NULL,
                                   email VARCHAR(80) UNIQUE NOT NULL,
                                   password VARCHAR(50) NOT NULL,
                                   token VARCHAR(255),
                                   PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_logs(
                                        user_id BIGINT NOT NULL,
                                        log_id BIGINT NOT NULL
);

ALTER TABLE user_logs ADD CONSTRAINT UK_9vxsexu9hipl8nnmamgcowrqr UNIQUE (log_id);
ALTER TABLE log ADD CONSTRAINT FKjo7173o065h9iwe4nnkyo89iv FOREIGN KEY (user_id) REFERENCES user;
ALTER TABLE user_logs ADD CONSTRAINT FKph3wjwm73jt12cghsk7k4o1ba FOREIGN KEY (log_id) REFERENCES log;
ALTER TABLE user_logs ADD CONSTRAINT FKcitdrh6cbs22gb0s9ug2i4i2c FOREIGN KEY (user_id) REFERENCES user;
